# goreleaser config for iofogctl. See: https://goreleaser.com
#
# To execute goreleaser, use the mage targets:
#
#  $ mage iofogctl:snapshot
#  $ mage iofogctl:release
#
# The snapshot target builds the installation packages (brew, rpm,
# deb, etc), into the dist dir.
# The release target does the same, but also publishes the packages.
#
# See README.md for more.
version: 2
project_name: iofogctl
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - go version

builds:
  - id: build_macos
    binary: iofogctl
    env:
      - CGO_ENABLED=0
    main: ./cmd/iofogctl/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=containers_image_openpgp,exclude_graphdriver_btrfs
    ldflags:
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.operatorTag=3.7.2"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.routerTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerTag=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerVersion=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentVersion=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.debuggerTag=latest"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.natsTag=3.6.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.repo=ghcr.io/eclipse-iofog"

  - id: build_linux_amd64
    binary: iofogctl
    main: ./cmd/iofogctl/
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -v
      - -tags=containers_image_openpgp,exclude_graphdriver_btrfs
    ldflags:
      - -extldflags -static
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.operatorTag=3.7.2"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.routerTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerTag=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerVersion=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentVersion=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.natsTag=3.6.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.repo=ghcr.io/eclipse-iofog"

  - id: build_linux_arm64
    binary: iofogctl
    main: ./cmd/iofogctl/
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_ENABLED=1
    flags:
      - -v
      - -tags=containers_image_openpgp,exclude_graphdriver_btrfs
    ldflags:
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.operatorTag=3.7.2"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.routerTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerTag=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerVersion=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentVersion=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.natsTag=3.6.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.repo=ghcr.io/eclipse-iofog"

  - id: build_linux_arm
    binary: iofogctl
    main: ./cmd/iofogctl/
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
      - 7
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_ENABLED=1
    flags:
      - -v
      - -tags=containers_image_openpgp,exclude_graphdriver_btrfs
    ldflags:
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.operatorTag=3.7.2"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.routerTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerTag=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerVersion=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentVersion=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.debuggerTag=latest"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.natsTag=3.6.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.repo=ghcr.io/eclipse-iofog"

  - id: build_windows
    binary: iofogctl
    env:
      - CGO_ENABLED=0
    main: ./cmd/iofogctl/main.go
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=containers_image_openpgp,exclude_graphdriver_btrfs
    ldflags:
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.operatorTag=3.7.2"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.routerTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerTag=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentTag=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.controllerVersion=3.7.3"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.agentVersion=3.7.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.debuggerTag=latest"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.natsTag=3.6.0"
      - -s -w -X "github.com/eclipse-iofog/iofogctl/pkg/util.repo=ghcr.io/eclipse-iofog"


archives:
  -
    id: linux
    ids:
      - build_linux_amd64
      - build_linux_arm64
      - build_linux_arm
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: [ 'tar.gz' ]
    files:
      - README.md
      - LICENSE
  -
    id: macos
    ids:
      - build_macos
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os `darwin` }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}"
    formats: [ 'tar.gz' ]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{.ProjectName}}-checksums.txt"

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT"

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch


release:
  github:
    owner: eclipse-iofog
    name: iofogctl

  # If set to true, will not auto-publish the release. Default is false.
  draft: false

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

brews:
  -
    name: iofogctl
    homepage: "https://github.com/eclipse-iofog/iofogctl"
    description: "CLI for ioFog"
    goarm: 6

    repository:
      owner: eclipse-iofog
      name: homebrew-iofogctl
      

    url_template: "https://github.com/eclipse-iofog/iofogctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: emirhandurmus
      email: emirhan.durmus@datasance.com

    directory: Formula

    test: |
      system "#{bin}/iofogctl version"
    install: |
      bin.install "iofogctl"
    skip_upload: false

nfpms:
  -
    ids: ['build_linux_amd64', 'build_linux_arm64', 'build_linux_arm']
    homepage:  "https://github.com/eclipse-iofog/iofogctl"
    description: CLI for ioFog
    maintainer: Contributors to the Eclipse ioFog Project
    vendor: Datasance


    formats:
      - deb
      - rpm
      - apk

    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      rpm:
         file_name_template: "{{ .ProjectName }}-{{ .Version }}-1.{{ if eq .Arch `amd64` }}x86_64{{ else if eq .Arch `arm64` }}aarch64{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}hl{{ end }}"
      apk:
        file_name_template: "{{ .ConventionalFileName }}"