#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

set -e

echo "Pre commit:"
echo "Building..."
make lint
make iofogctl potctl
echo "Generating docs..."
./bin/iofogctl documentation md -o ./docs/iofogctl_md
./bin/potctl documentation md -o ./docs/potctl_md
echo "Patching docs..."
find ./docs/iofogctl_md ./docs/potctl_md -type f | xargs sed -i '' 's/.*Auto generated.*//g'
find ./docs/iofogctl_md ./docs/potctl_md -type f | xargs sed -E -i '' 's/(command within \(default).*/\1 "default")/g'
echo "Adding docs to the commit..."
git add ./docs/iofogctl_md ./docs/potctl_md
