#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

set -e

echo "Pre commit:"
echo "Formatting..."
make fmt
echo "Generating docs..."
make build
./bin/iofogctl documentation md -o ./docs/
echo "Adding docs to the commit..."
git add ./docs/
