jobs:
- job: K8s
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: iofogctl
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: |
      sudo cp iofogctl/build_linux_linux_amd64/iofogctl /usr/local/bin/
      sudo chmod 0755 /usr/local/bin/iofogctl
  - template: steps/postinstall.yaml
  - template: steps/init-ssh.yaml
  - template: steps/init-vms.yaml
    parameters:
      id: $(jobuuid)
      distro: $(gcp.vm.distro.buster)
      repo: $(gcp.vm.repo.debian)
      agent_count: 2
      controller_count: 0
  - script: |
      set -e
      keyFilePath="$(Agent.TempDirectory)/azure-gcp.json"
      
      # Install gcloud-auth-plugin
      echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl -f https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
      
      gcloud components list
      
      gcloud --quiet auth activate-service-account --key-file="${keyFilePath}"
      gcloud --quiet container clusters get-credentials $(gcp.cluster.name) --region $(gcp.cluster.region)
    displayName: 'Connect to cluster'
  - template: steps/configure-remote-tests.yaml
  - template: steps/install-test-deps.yaml
  - script: |
      set -o pipefail
      test/run.bash k8s | tee test/conf/results-k8s.tap
    displayName: 'Run Functional Tests'
  - script: |
      tap-junit -i test/conf/results-k8s.tap -o test/conf -s K8s -n results-k8s.xml || true
    displayName: 'Convert test output from TAP to JUnit'
    condition: succeededOrFailed()
  - script: |
        test/clean.bash
    displayName: 'Clean K8s Cluster'
    condition: always()
  - template: steps/functional-post-test.yaml
  - template: steps/functional-clean-vm.yaml
    parameters:
      id: $(jobuuid)
      agent_count: 2
      controller_count: 0