jobs:
- job: Local
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - template: steps/init-gcloud-steps.yaml
  - script: |
      gcloud --quiet auth configure-docker
      docker pull $(controller_image)
      docker pull $(agent_image)
    displayName: 'Pull develop gcr docker image'
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: iofogctl
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: |
      sudo cp iofogctl/build_linux_linux_amd64/iofogctl /usr/local/bin/
      sudo chmod 0755 /usr/local/bin/iofogctl
  - bash: |
      sudo apt-get install -y jq
    displayName: 'Install jq'
  - template: steps/postinstall.yaml
  - template: steps/configure-remote-tests.yaml
  - template: steps/install-test-deps.yaml
  - script: |
      test/run.bash smoke
    displayName: 'Run Smoke Tests'
  - script: |
      set -o pipefail
      test/run.bash local | tee test/conf/results-local.tap
    displayName: 'Run Functional Tests'
  - script: |
      tap-junit -i test/conf/results-local.tap -o test/conf -s Local -n results-local.xml || true
    displayName: 'Convert test output from TAP to JUnit'
    condition: succeededOrFailed()
  - template: steps/functional-post-test.yaml
  - script: |
      docker system prune -af
    condition: always()
    displayName: 'Clean local docker'