jobs:
- job: OSX
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: darwin
      downloadPath: $(System.DefaultWorkingDirectory)
  - template: steps/init-gcloud-steps.yaml
  - template: steps/version.yaml
  - template: steps/init-ssh.yaml
  - script: |
      . version
      short_version=$MAJOR.$MINOR.$PATCH
      tar -zcf iofogctl.tar.gz darwin/iofogctl
      checksum=$(shasum -a 256 iofogctl.tar.gz | awk '{ print $1 }')
      gsutil cp iofogctl.tar.gz gs://$(gcp.bucket.osx)/$short_version/
      gsutil acl set public-read  gs://$(gcp.bucket.osx)/$short_version/iofogctl.tar.gz
      git config --global user.email "serge@edgeworx.io"
      git config --global user.name "Serge Radinovich"
      git clone git@github.com:eclipse-iofog/homebrew-iofogctl.git
      cd homebrew-iofogctl
      brew_file=iofogctl@${MAJOR}.${MINOR}-devel.rb
      if [ ! -f $brew_file ]; then
        cat ../pipeline/brew.tpl > $brew_file
        sed -i "s/<AT_VERSION>/${MAJOR}${MINOR}Devel/g" $brew_file
        sed -i "s/<SHA256>/$checksum/g" $brew_file
        sed -i "s/<URL>/$(gcp.bucket.url)/g" $brew_file
        sed -i "s/<BUCKET>/$(gcp.bucket.osx)/g" $brew_file
        sed -i "s/<VERSION>/$(version)/g" $brew_file
      else
        sed -i "s/sha256.*/sha256 \"$checksum\"/g" $brew_file
        sed -i "s/version.*/version \"$(version)\"/g" $brew_file
        sed -i "s|url .*|url \"$(gcp.bucket.url)/$(gcp.bucket.osx)/$short_version/iofogctl.tar.gz\"|g" $brew_file
      fi
      git add $brew_file
      git commit -m "Publish develop version $(version)"
      git push origin master
    displayName: 'Build and publish OSX binary'