jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: linux
      downloadPath: $(System.DefaultWorkingDirectory)
  - template: steps/init-gcloud-steps.yaml
  - template: steps/version.yaml
  - template: steps/init-ssh.yaml
  - script: |
      . version.sh
      DIR="$(gcp.bucket.linux)/$MAJOR.$MINOR"
      gsutil cp linux/iofogctl gs://$DIR/iofogctl
      gsutil acl set public-read  gs://$DIR/iofogctl
    displayName: 'Publish Linux binary'
 