jobs:
- job: Windows
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: windows
      downloadPath: $(System.DefaultWorkingDirectory)
  - template: steps/init-gcloud-steps.yaml
  - template: steps/version.yaml
  - template: steps/init-ssh.yaml
  - script: |
      . version
      DIR="$(gcp.bucket.win)/$MAJOR.$MINOR"
      gsutil cp windows/iofogctl gs://$DIR/iofogctl.exe
      gsutil acl set public-read  gs://$DIR/iofogctl.exe
    displayName: 'Publish Windows binary'
 