parameters:
  job_name: ''
  id: ''
  distro: ''
  repo: ''
  agent_count: 1
  controller_count: 1

jobs:
- job: ${{ parameters.job_name }}
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
    - template: steps/vanilla.yaml
      parameters:
        id: $(jobuuid)
        distro: $(distro)
        repo: $(repo)
        agent_count: 2
        controller_count: 1