parameters:
  job_name: ''
  id: ''
  distro: ''
  repo: ''
  agent_count: 1
  controller_count: 1

jobs:
- job: ${{ parameters.job_name }}
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
    - template: steps/vanilla.yaml
      parameters:
        id: $(jobuuid)
        distro: ${{ parameters.distro }}
        repo: ${{ parameters.repo }}
        agent_count: 2
        controller_count: 1