jobs:
- job: Debian
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: linux
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: |
      sudo cp linux/iofogctl /usr/local/bin/
      sudo chmod 0755 /usr/local/bin/iofogctl
  - template: version-steps.yaml
  - template: publish-deps.yaml
  - script: |
      fpm -f -s dir -t deb -n iofogctl -v $(version) /usr/local/bin/iofogctl=/usr/local/bin/
      package=$(ls | grep *.deb)
      echo $package
      cp $package $(Build.ArtifactStagingDirectory)
    displayName: 'Create Debian package'
  - script: |
      package=$(ls | grep *.deb)
      echo "package..."
      echo $package
      declare -a UBUNTU_VERS=("xenial" "bionic")
      declare -a DEBIAN_VERS=("stretch" "buster")
      for ubu in "${UBUNTU_VERS[@]}"
      do
          package_cloud yank iofog/iofogctl-snapshots/ubuntu/${ubu} $package --config=$(Agent.TempDirectory)/package_cloud || true
          package_cloud push iofog/iofogctl-snapshots/ubuntu/${ubu} $package --config=$(Agent.TempDirectory)/package_cloud
      done
      for deb in "${DEBIAN_VERS[@]}"
      do
          package_cloud yank iofog/iofogctl-snapshots/debian/${deb} $package --config=$(Agent.TempDirectory)/package_cloud || true
          package_cloud push iofog/iofogctl-snapshots/debian/${deb} $package --config=$(Agent.TempDirectory)/package_cloud
      done
    displayName: 'Publish deb to package-cloud'
