name: CI
on:
  push:
    branches:
      - develop
      - release*
    tags: [v*]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop
      - release*
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
env:
  PROJECT: 'focal-freedom-236620'
  IMAGE_NAME: 'operator'
  GKE_CLUSTER: 'iofogctl-ci'
  GKE_ZONE: 'us-central1-a'
  controller_image: 'gcr.io/focal-freedom-236620/controller:develop'
  enterprise_image: 'gcr.io/focal-freedom-236620/enterprise-controller:master'
  agent_image: 'gcr.io/focal-freedom-236620/agent:develop'
  operator_image: 'gcr.io/focal-freedom-236620/operator:develop'
  kubelet_image: 'gcr.io/focal-freedom-236620/kubelet:develop'
  port_manager_image: 'gcr.io/focal-freedom-236620/port-manager:develop'
  router_image: 'gcr.io/focal-freedom-236620/router:develop'
  router_arm_image: 'gcr.io/focal-freedom-236620/router-arm:develop'
  proxy_image: 'gcr.io/focal-freedom-236620/proxy:3.0.0-beta1'
  proxy_arm_image: 'gcr.io/focal-freedom-236620/proxy-arm:develop'
  iofog_agent_version: '0.0.0-dev'
  controller_version: '0.0.0-dev'
  version:
  agent_vm_list:
  controller_vm:
  windows_ssh_key_path: 'C:/Users/$(azure.windows.user)/.ssh'
  ssh_key_file: 'id_rsa'
  windows_kube_config_path: 'C:/Users/$(azure.windows.user)/.kube/config'
  bash_kube_config_path: '/root/.kube/config'

jobs:
  Build:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18'
          cache: false
      - run: go version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --timeout=5m0s
      - name: Run bootstrap
        run: PIPELINE=1 script/bootstrap.sh
      - run: make test
      - name: iofogctl build packages GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 1.1.0
          args: --snapshot --rm-dist --debug --config ./.goreleaser-iofogctl.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iofogctl
          path: ${{ github.workspace }}/dist
  Windows_Test:
    needs: Build
    runs-on: windows-latest
    steps:
      - name: Display the path
        run: echo %PATH%
        shell: cmd
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
         name: iofogctl
      - run: ls
      - name: Prepare iofogctl binary
        shell: cmd
        run: |
          echo "::add-path::${{ github.workspace }}/build_windows_windows_amd64/iofogctl/iofogctl"
          ${{ github.workspace }}/build_windows_windows_amd64/iofogctl version
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - run: bats --version
      - uses: azure/setup-kubectl@v3
        id: install
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT }}
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - name: run Functional Test
        run: sh test/run.bash k8s
