name: govulncheck

on:
  push:
    paths:
      - go.sum
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions: read-all

env:
  GO_VERSION: '1.26.4'

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

      - name: Run govulncheck
        run: |
          chmod +x scripts/vulncheck.sh
          scripts/vulncheck.sh

      - name: Verify module integrity
        run: go mod verify
